[tools]
node = "lts"
"npm:@styled/typescript-styled-plugin" = "latest"
"npm:pretty-ts-errors-markdown" = "latest"

ruby = "latest"
"gem:tmuxinator" = "latest"

rust = "latest"
go = "latest"
python = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
compile = false
