[tools]
node = "lts"
ruby = "latest"
rust = "latest"
go = "latest"
python = "latest"
bun = "latest"

"npm:@styled/typescript-styled-plugin" = "latest"
"npm:pretty-ts-errors-markdown" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@colbymchenry/codegraph" = "latest"

# For claude lsp servers, I primarily use vtsls instead
"npm:typescript-language-server" = "latest"

"npm:@vtsls/language-server" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@t1ckbase/vscode-langservers-extracted" = "latest"
"npm:css-variables-language-server" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:prettier" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:yaml-language-server" = "latest"

"github:LuaLS/lua-language-server" = "latest"
"github:artempyanykh/marksman" = "latest"
"github:johnnymorganz/stylua" = "latest"
"github:tamasfe/taplo" = "latest"
"github:tree-sitter/tree-sitter" = "latest"
"github:tekumara/typos-lsp" = "latest"
"github:rust-lang/rust-analyzer" = "latest"

"github:burntsushi/ripgrep" = "latest"
"github:junegunn/fzf" = "latest"
"github:sharkdp/fd" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:jqlang/jq" = "latest"

"go:golang.org/x/tools/gopls" = "latest"
"gem:tmuxinator" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age = "1d"

[settings.ruby]
compile = false
