[tools]
node = "lts"
ruby = "latest"
rust = "latest"
go = "latest"
python = "latest"
bun = "latest"

"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@colbymchenry/codegraph" = "latest"
"npm:pretty-ts-errors-markdown" = "latest"
"npm:@styled/typescript-styled-plugin" = "latest"
"npm:typescript" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@t1ckbase/vscode-langservers-extracted" = "latest"
"npm:css-variables-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:yaml-language-server" = "latest"

"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:prettier" = "latest"
"npm:skills" = "latest"

"go:golang.org/x/tools/gopls" = "latest"

"gem:tmuxinator" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age = "1d"

[settings.ruby]
compile = false
