---@class configs.icons
local M = {
  misc = {
    dots = '󰇘',
    tab = ' ',
    spinner_frames = { '󰄰', '󰪞', '󰪟', '󰪠', '󰪢', '󰪣', '󰪤', '󰪥' },
  },
  ft = {
    octo = '',
  },
  input = {
    prompt_prefix = '  ',
  },
  dap = {
    Stopped = { '󰁕 ', 'DiagnosticWarn', 'DapStoppedLine' },
    Breakpoint = ' ',
    BreakpointCondition = ' ',
    BreakpointRejected = { ' ', 'DiagnosticError' },
    LogPoint = '.>',
  },
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  file_status = {
    -- modified = '',
    -- modified = ' ',
    -- modified = '󱗜 ',
    modified = '󰪥 ',
    readonly = '󰌾 ',
    new = ' ',
    unnamed = '',
  },
  git = {
    added = ' ',
    modified = ' ',
    removed = ' ',
    unstaged = '󰄱',
    staged = '',
    unmerged = '',
    renamed = '󰁕',
    untracked = '',
    deleted = '',
    ignored = '',
  },
  explorer = {
    selected = ' 󰪥 ',
    unselected = ' 󰄰',
    collapsed = '',
    expanded = '',
    folder = '󰉋',
    folder_open = '󰝰',
    folder_empty = '',
    folder_empty_open = '',
    folder_symlink = '',
  },
  kinds = {
    Array = ' ',
    Boolean = '󰨙 ',
    Class = ' ',
    Codeium = '󰘦 ',
    Color = ' ',
    Control = ' ',
    Collapsed = ' ',
    Constant = '󰏿 ',
    Constructor = ' ',
    Copilot = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = '󰉋 ',
    Function = '󰊕 ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = '󰊕 ',
    Module = ' ',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = '󱄽 ',
    String = ' ',
    Struct = '󰆼 ',
    Supermaven = ' ',
    TabNine = '󰏚 ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = '󰀫 ',
  },
}

return M
