return {
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  version = false, -- last release is way too old and doesn't work on Windows
  build = ':TSUpdate',
  event = { 'BufReadPost', 'BufNewFile', 'BufWritePre', 'VeryLazy' },
  cmd = { 'TSUpdate', 'TSInstall', 'TSLog', 'TSUninstall' },
  opts_extend = { 'ensure_installed' },
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    folds = { enable = true },
    ensure_installed = {
      'bash',
      'c',
      'diff',
      'html',
      'javascript',
      'jsdoc',
      'json',
      'jsonc',
      'lua',
      'luadoc',
      'luap',
      'markdown',
      'markdown_inline',
      'printf',
      'python',
      'query',
      'regex',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
      'css',
      'styled',
      'zsh',
    },
  },
}
