# [[ Config reload ]]
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# [[ Splits, windows & sessions ]]
bind - split-window -v
bind \\ split-window -h
bind n new-window
bind N new-session

# cmd+[ / cmd+] => prev/next window, no prefix. See ghostty config
bind -n M-h previous-window
bind -n M-l next-window

# [[ Copy mode ]]
bind Escape copy-mode
bind -T copy-mode-vi i send -X cancel
bind -T copy-mode-vi a send -X cancel

bind -T copy-mode-vi PageUp   send -X halfpage-up   \; send -X scroll-middle
bind -T copy-mode-vi PageDown send -X halfpage-down \; send -X scroll-middle

# Make 'v' act like Vim's char-wise visual
unbind -T copy-mode-vi v
bind   -T copy-mode-vi v send -X begin-selection
