unbind r
bind r source-file ~/.tmux.conf
bind - split-window -v
bind \\ split-window -h

bind -T copy-mode-vi PageUp   send -X halfpage-up   \; send -X scroll-middle
bind -T copy-mode-vi PageDown send -X halfpage-down \; send -X scroll-middle

bind Escape copy-mode
bind -T copy-mode-vi i send -X cancel
bind -T copy-mode-vi a send -X cancel
# --- Make 'v' act like Vim's char-wise visual ---
unbind -T copy-mode-vi v 
bind   -T copy-mode-vi v send -X begin-selection

bind n new-window
bind N new-session

# cmd+[ / cmd+] => prev/next window, no prefix. See ghostty config
set -s user-keys[0] "\e[5;30013~"
set -s user-keys[1] "\e[5;30014~"
bind -n User0 previous-window
bind -n User1 next-window
