#!/bin/zsh

build-tmux() {
  cd ~/Repositories/personal/tmux \
    && sh autogen.sh \
    && ./configure --enable-utf8proc \
    && make clean \
    && make \
    && sudo make install \
    && cd -
}
