#!/bin/zsh

# [Y]azi [C]hange [D]irectory
# Press q to quit and cd into the cwd
# Press Q to quit without changing directory
function ycd {
  local cwd_file
  cwd_file=$(mktemp)
  yazi --cwd-file="$cwd_file" "$@"
  if [ -f "$cwd_file" ]; then
    z "$(cat "$cwd_file")" || return
    rm "$cwd_file"
  fi
}
