--- @class config.icons
local M = {
  misc = {
    ARROW = '',
    DOTS = '󰇘',
    TAB = '',
    LOCATION = '',
    NEOVIM = '',
    MACRO = ' ',
    TAILWIND_COLOR = '',
    PACKAGE_ACTIVE = '󰪥',
    PACKAGE_INACTIVE = '󰄰',
    PENDING_KEYS = '󰌌',
    PILL_LEFT = '',
    PILL_RIGHT = '',
    QUOTE_BAR = '▌',
  },
  ft = {
    OCTO = '',
    TYPESCRIPT = '',
  },
  input = {
    PROMPT_PREFIX = '  ',
    SELECTION_CARET = ' ',
  },
  diagnostics = {
    ERROR = ' ',
    WARN = ' ',
    HINT = ' ',
    INFO = ' ',
  },
  file_status = {
    MODIFIED = '󰪥 ',
    READONLY = '󰌾 ',
    NEW = '󰎔 ',
    UNNAMED = '',
  },
  git = {
    GIT = '󰊢',
    SIGN = '',
    HUNK = '┃',
    HUNK_DELETE = '',
    BRANCH = '',
    ADDED = ' ',
    MODIFIED = ' ',
    REMOVED = ' ',
    UNSTAGED = '󰄮',
    STAGED = '󰄲',
    UNMERGED = '',
    RENAMED = '󰁕',
    UNTRACKED = '',
    DELETED = '',
    IGNORED = '',
    BLAME = ' ',
    DIFF = '',
  },
  file_tree = {
    HOME = ' ',
    SELECTED = ' 󰪥 ',
    UNSELECTED = ' 󰄰',
    COLLAPSED = '',
    EXPANDED = '',
    FOLDER = '󰉋',
    FOLDER_OPEN = '',
    FOLDER_EMPTY = '',
    FOLDER_EMPTY_OPEN = '',
    FOLDER_SYMLINK = '',
  },
  -- Unlike every other group, these leaf keys stay PascalCase instead of
  -- CONSTANT_CASE: they are consumed as-is as blink-cmp `kind_icons` keys
  -- (see features/completion/blink-cmp/config/appearance.lua) and must match
  -- the LSP CompletionItemKind names (Array, Boolean, Class, ...) verbatim.
  cmp_kinds = {
    -- lspkind.nvim codicon preset
    Array = ' ',
    Boolean = '󰨙 ',
    Class = '',
    Codeium = '󰘦 ',
    Color = '',
    Control = ' ',
    Collapsed = ' ',
    Constant = '',
    Constructor = '',
    Claude = '✻',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '',
    File = '',
    Folder = '󰉋',
    Function = '',
    Interface = '',
    Key = ' ',
    Keyword = '',
    Method = '',
    Module = '',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = '',
    Package = ' ',
    Property = '',
    Reference = '',
    Snippet = '',
    Spell = '',
    String = ' ',
    Struct = '',
    Supermaven = ' ',
    TabNine = '󰏚 ',
    Text = '',
    TypeParameter = '',
    Unit = '',
    Value = '',
    Variable = '',

    History = '',
    Yanky = '󰨸',
    RenderMD = '',
    Minuet = ' ',
    CodingAgent = '󰚩 ',
  },
  file_icons = {
    KEEP = '󰊢',
    DEVCONTAINER = '',
    ESLINT = '󰱺',
    ESLINT_CONFIG = '󰱺',
    NODE_VERSION = '',
    PRETTIERRC = '',
    YARNRC = '',
    PACKAGE_JSON = '',
    TSCONFIG = '',
    TSCONFIG_BUILD = '',
    YARN_LOCK = '',
    DOTENV = '',
    SQL = '󰆼',
    ICO = '',
    TEXT = '󰦨',
    SCHEME = '',
    MARKDOWN = '',
    HANDLEBARS = '',
  },
  editor = {
    TERMINAL = '',
    WINDOW = '',
    BUFFER = '',
    HELP = '󰋗',
    KEYMAPS = '',
    REGISTER = '',
    HIGHLIGHT = '',
    PROMPT = '󰍩',
    URL = '',
    DIAGNOSTIC = '󱖫',
    NOTIFICATION = '',
    DISMISS_NOTIFICATION = '󱏧',
    SHOW_NOTIFICATION = '󱅫',
    IMAGE = '',
  },
  tools = {
    PLUGIN_MANAGER = '󰏓',
    SESSION = '󰆓',
    FLASH = '',
    LSP = ' ',
    DEBUG = '󰃤',
    MULTICURSOR = '',
    SURROUND = '󰗅 ',
    BREADCRUMB = '',
    TREE = ' ',
    CODE = '',
    PIN = '󰐃',
  },
  navigation = {
    PREV = '󰒮',
    NEXT = '󰒭',
    UP = '',
    DOWN = '',
    LEFT = '',
    RIGHT = '',
    CYCLE = '',
    SCROLL_UP = '󱕑 ',
    SCROLL_DOWN = '󱕐 ',
  },
  -- Telescope borderchars layout, see:
  -- https://github.com/nvim-telescope/telescope.nvim/blob/5972437de807c3bc101565175da66a1aa4f8707a/lua/telescope/themes.lua#L50
  -- The `prompt`/`results`/`preview` leaf keys stay lowercase (rather than
  -- CONSTANT_CASE) because Telescope reads them verbatim from `borderchars`.
  telescope_borders = {
    prompt = { '─', '│', ' ', '│', '╭', '╮', '│', '│' },
    -- Disconnected edges, similar to snacks picker
    results = { '─', '│', '─', '│', '│', '│', '╯', '╰' },
    preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
  },
  fillchars = {
    DIFF = '╱',
  },
  actions = {
    YANK = '',
    UNDO = '',
    RENAME = '󰑕',
    DELETE = '󰗨',
    PASTE = '',
    PEEK = '󰈈',
    FOLD = '',
    RESET = '󰑓',
    CUT = '',
    ADD = '',
    COMMENT = '󰿠',
    CODE_ACTION = '',
    GREP = ' ',
    SEARCH = ' ',
    FIND = ' ',
    SEND_FILE = '󰈪',
    AROUND = '󰭶',
    INSIDE = '󰹗',
    NEWLINE = '',
  },
}

return M
