---@class config.icons
local M = {
  misc = {
    dots = '󰇘',
    tab = ' ',
    pin = '󰐃',
    location = '',
    neovim = '',
    macro = ' ',
    tailwind_color = '',
    package_active = '󰪥',
    package_inactive = '󰄰',
    pending_keys = '󰌌',
    pill_left = '',
    pill_right = '',
    quote_bar = '▌',
  },
  ft = {
    octo = '',
    typescript = '',
  },
  input = {
    prompt_prefix = '  ',
    selection_caret = ' ',
  },
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  file_status = {
    modified = '󰪥 ',
    readonly = '󰌾 ',
    new = '󰎔 ',
    unnamed = '',
  },
  git = {
    git = '󰊢',
    sign = '',
    hunk = '┃',
    hunk_delete = '',
    branch = '',
    added = ' ',
    modified = ' ',
    removed = ' ',
    unstaged = '󰄮',
    staged = '󰄲',
    unmerged = '',
    renamed = '󰁕',
    untracked = '',
    deleted = '',
    ignored = '',
    blame = ' ',
    diff = '',
  },
  explorer = {
    home = ' ',
    selected = ' 󰪥 ',
    unselected = ' 󰄰',
    collapsed = '',
    expanded = '',
    folder = '󰉋',
    folder_open = '',
    folder_empty = '',
    folder_empty_open = '',
    folder_symlink = '',
  },
  kinds = {
    -- lspkind.nvim codicon preset
    Array = ' ',
    Boolean = '󰨙 ',
    Class = '',
    Codeium = '󰘦 ',
    Color = '',
    Control = ' ',
    Collapsed = ' ',
    Constant = '',
    Constructor = '',
    Claude = '✻',
    Copilot = '',
    CopilotEnabled = '',
    CopilotSleep = '',
    CopilotDisabled = '',
    CopilotWarning = '',
    CopilotUnknown = '',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '',
    File = '',
    Folder = '󰉋',
    Function = '',
    Interface = '',
    Key = ' ',
    Keyword = '',
    Method = '',
    Module = '',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = '',
    Package = ' ',
    Property = '',
    Reference = '',
    Snippet = '',
    Spell = '',
    String = ' ',
    Struct = '',
    Supermaven = ' ',
    TabNine = '󰏚 ',
    Text = '',
    TypeParameter = '',
    Unit = '',
    Value = '',
    Variable = '',

    History = '',
    Yanky = '󰨸',
    RenderMD = '',
    Minuet = ' ',
  },
  file_icons = {
    keep = '󰊢',
    devcontainer = '',
    eslint = '󰱺',
    eslint_config = '󰱺',
    node_version = '',
    prettierrc = '',
    yarnrc = '',
    package_json = '',
    tsconfig = '',
    tsconfig_build = '',
    yarn_lock = '',
    dotenv = '',
    sql = '󰆼',
  },
  editor = {
    terminal = '', -- auto-session
    window = ' ',
    buffer = '',
    help = '󰋗',
    keymaps = ' ',
    register = '',
    highlight = '',
    prompt = '󰍩',
    url = ' ',
    diagnostic = '󱖫 ',
    notification = '',
    dismiss_notification = '󱏧',
    show_notification = '󱅫',
    image = ' ',
  },
  tools = {
    session = '󰆓',
    harpoon = '󰛢',
    lsp = ' ',
    mason = ' ',
    eagle = '󱗆',
    debug = '󰃤',
    multicursor = '',
    surround = '󰗅 ',
    breadcrumb = '', -- Dropbar
    tree = ' ', -- nvim-tree
    code = '',
  },
  navigation = {
    prev = '󰒮',
    next = '󰒭',
    up = '',
    down = '',
    left = '',
    right = '',
    cycle = '',
    scroll_up = '󱕑 ',
    scroll_down = '󱕐 ',
  },
  borders = {
    -- Telescope borderchars layout, see:
    -- https://github.com/nvim-telescope/telescope.nvim/blob/5972437de807c3bc101565175da66a1aa4f8707a/lua/telescope/themes.lua#L50
    telescope = {
      prompt = { '─', '│', ' ', '│', '╭', '╮', '│', '│' },
      -- Connected edges:
      -- results = { '─', '│', '─', '│', '├', '┤', '╯', '╰' },
      -- Disconnected edges, similar to snacks picker
      results = { '─', '│', '─', '│', '│', '│', '╯', '╰' },
      preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
    },
  },
  actions = {
    yank = '',
    undo = '',
    rename = '󰑕',
    delete = '󰗨',
    paste = '',
    peek = '󰈈',
    fold = '',
    reset = '󰑓',
    cut = '',
    add = '',
    comment = '󰿠',
    code_action = '',
    grep = ' ',
    search = ' ',
    find = ' ',
    send_file = '󰈪',
    around = '󰭶',
    inside = '󰹗',
    newline = '',
  },
}

return M
