#!/bin/zsh

# [N]eo[V]im and [C]hange [D]irectory
function nvcd {
  # 1. The `env TERM=wezterm` is for https://wezfurlong.org/wezterm/faq.html#how-do-i-enable-undercurl-curly-underlines
  # 2. Have to use the `command` to explicitly call a command without triggering the alias.
  if [[ -z $1 ]]; then
    command env TERM=wezterm nvim
    return 0
  fi

  if [[ -d $1 ]]; then
    z "$1" && command env TERM=wezterm nvim .
    return 0
  fi

  command env TERM=wezterm nvim "$1"
}
