# This theme is based on Catppuccin Mocha (Copyright (c) 2021 Catppuccin, released
# under the MIT license, https://github.com/catppuccin/catppuccin)

# comments
"comment" = "#9399b2"

# strings
"string" = "#a6e3a1"

# regular expressions
"keyword.operator.regexp" = "#f5c2e7"

# escape characters
"constant.character" = "#f5c2e7"

# constants in general
"constant" = "#fab387"

# parameters
"variable.parameter" = "#eba0ac"

# environment variables
"variable.other" = "#fab387"
"punctuation.definition.variable" = "#fab387"

# commands
"variable.function" = "#89b4fa"

# home directory ~
"variable.language.tilde" = "#fab387"

# keywords
"keyword" = "#cba6f7"

# general foreground color
source = "#cdd6f4"

# variable assignments
"storage" = "#f9e2af"
"storage.modifier" = "#cba6f7"

# support terms (e.g. double braces, let)
"support" = "#89b4fa"
"keyword.operator" = "#94e2d5"

# function names
"entity.name.function" = "#89b4fa"

# braces
"punctuation.section" = "#9399b2"

# terminators (e.g. ";;" after a case item)
"punctuation.terminator" = "#9399b2"

# history expansions
"meta.group.expansion.history" = "#b4befe"

# reset command substitutions to the theme's default foreground color
"meta.group.expansion.command.parens" = { foreground = "#cdd6f4" }

# dynamic items
"dynamic.callable" = "#a6e3a1"
"dynamic.callable.missing" = "#f38ba8"
"dynamic.path" = { underline = true }
