[metadata]
name = "dotfiles"
description = "A channel to select dotfiles configs"
requirements = ["fd", "eza", "nvim"]

[ui]
layout = "landscape"
input_bar = { header = "Dotfiles", prompt = "  " }

[source]
ansi = true
command = "fdt '^\\.config$' $HOME/Repositories/personal/dotfiles --exec zsh -c 'eza \"$1\"' _ {}"
output = "{strip_ansi|substring:1..}"

[preview]
command = "cd $HOME/Repositories/personal/dotfiles/{strip_ansi|substring:2..}/.config; eza --tree {strip_ansi|substring:2..}"

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open selected files in editor"
command = "nvim $HOME/Repositories/personal/dotfiles/{strip_ansi|substring:2..}/.config/{strip_ansi|substring:2..}"
