[metadata]
name = "dotfiles"
description = "A channel to select dotfiles configs"
requirements = ["fd", "eza", "nvim"]

[ui]
layout = "landscape"
input_bar = { header = "Dotfiles", prompt = "  " }

[source]
command = "fdt '^\\.config$' $HOME/Repositories/personal/dotfiles --exec zsh -c 'ls \"$1\"' _ {}"

[preview]
command = "cd $HOME/Repositories/personal/dotfiles/{}/.config; eza --tree {}"

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open selected files in editor"
command = "nvim $HOME/Repositories/personal/dotfiles/{}/.config/{}"
