[metadata]
name = "files"
description = "A channel to select files"
requirements = ["fd", "bat", "eza", "nvim"]

[ui]
layout = "portrait"
input_bar = { header = "Files", prompt = "  " }

[source]
ansi = true
command = "fd -t f --exec eza --icons=always --color=always"
output="{strip_ansi|substring:1..}"

[preview]
# https://docs.rs/string_pipeline/0.12.0/string_pipeline/
command = "bat -n --color=always {strip_ansi|substring:1..}"

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open selected files in editor"
command = "nvim {strip_ansi|substring:1..}"